### ISSUE TITLE
Implémenter les endpoints Auteur, Media

### ISSUE THREAD

**Issue by meilie389** [adriens/caldoches-api#2]
implémenter les endpoints des auteurs et des média
`/{cléAuteur}/{id}`
`/{cléAuteur}/random`
`/{cléAuteur}/`

**Comment by meilie389** [comment]
![image](https://user-images.githubusercontent.com/41884305/84856296-099a5d00-b0b2-11ea-9099-760ea2b8d564.png)
![image](https://user-images.githubusercontent.com/41884305/84856321-1b7c0000-b0b2-11ea-9999-fdf5ac94db20.png)
![image](https://user-images.githubusercontent.com/41884305/84856346-2b93df80-b0b2-11ea-811a-54822098318b.png)
![image](https://user-images.githubusercontent.com/41884305/84856392-4ebe8f00-b0b2-11ea-8409-8096bff14c30.png)

**Comment by adriens** [comment]
top

**Comment by meilie389** [comment]
`/auteurs`

![auteurs](https://user-images.githubusercontent.com/41884305/86990373-2aa12a00-c1e8-11ea-945b-db42607da8f8.png)


`/auteurs/{id}`

![auteurs_id](https://user-images.githubusercontent.com/41884305/86990395-3a207300-c1e8-11ea-89d1-7f1a372c821a.png)


`/auteurs/key/{cleAuteur}`

![auteurs_key_cleAuteur](https://user-images.githubusercontent.com/41884305/86990398-3b51a000-c1e8-11ea-9fa4-7e9f406b3883.png)


`/medias`

![medias](https://user-images.githubusercontent.com/41884305/86990400-3c82cd00-c1e8-11ea-9a7c-a6c6609c7215.png)


`/medias/{id}`

![medias_id](https://user-images.githubusercontent.com/41884305/86990414-3ee52700-c1e8-11ea-9856-71232d00cf8e.png)


`/medias/auteur/{cleAuteur}`

![medias_auteur_cleAuteur](https://user-images.githubusercontent.com/41884305/86990407-3d1b6380-c1e8-11ea-996e-b8840974a0b3.png)


`/medias/auteur/{cleAuteur}/{id}`

![medias_auteur_cleAuteur_id](https://user-images.githubusercontent.com/41884305/86990409-3db3fa00-c1e8-11ea-9a1f-bb30ecc4d79f.png)


`/medias/auteur/{cleAuteur}/random`

![medias_auteur_cleAuteur_random_2](https://user-images.githubusercontent.com/41884305/86990412-3e4c9080-c1e8-11ea-91c8-f76d21f3c814.png)

![meidas_auteur_cleAuteur_random_1](https://user-images.githubusercontent.com/41884305/86990692-dcd8f180-c1e8-11ea-964d-44ba9df5e2a2.png)


`/types`

![types](https://user-images.githubusercontent.com/41884305/86990422-40aeea80-c1e8-11ea-89cb-7169f8411441.png)


`/types/{id}`

![types_id](https://user-images.githubusercontent.com/41884305/86990427-41e01780-c1e8-11ea-9534-1436aacfe74b.png)
